tags:
  - name: Authentication
    description: "Authenticate and begin a session"

paths:
  # Authentication
  /v2/login:
    post:
      tags: 
        - "Authentication"
      summary: Log In
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
                format: password
          required:
            - username
            - password
      responses:
        200:
          description: Log In Successful
        401:
          description: Log In Failed
        422:
          description: Invalid/Missing Parameters
      security:
      requestBody:
        - username
        - password
      callbacks:

  # Heartbeat
  /v2/heartbeat:
    get:
      tags: 
        - "Heartbeat"
      summary: Refreshes session token
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Heartbeat Detected
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  # Calendar
  /v2/cal/oneSummary/{class_id}:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - in: path
          name: class_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the class to get
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/oneFull/{class_id}:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - in: path
          name: class_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the class to get
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/userOrgSummary:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/userOrgFull:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/allSummary:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/allFull:
    get:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/addOne:
    post:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              class_name:
                type: string
              class_description:
                type: string
              address_id:
                type: integer
              date_of_class:
                type: integer
              time_of_class:
                type: string
              current_attendee_count:
                type: integer
              max_attendees:
                type: integer
              class_status:
                type: string
          required: true
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/cal/updateMyOne/{class_id}:
    put:
      tags:
        - "Calendar"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - in: path
          name: class_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the class to update
        - name: body
          in: body
          schema:
            type: object
            properties:
              class_name:
                type: string
              class_description:
                type: string
              address_id:
                type: integer
              date_of_class:
                type: integer
              time_of_class:
                type: string
              current_attendee_count:
                type: integer
              max_attendees:
                type: integer
              class_status:
                type: string
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  # Eligibility
  /v2/elig/myOrg:
    get:
      tags:
        - "Eligibility"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
      servers:
      requestBody:
      callbacks:
    put:
      tags:
        - "Eligibility"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              eligibility:
                type: object
          required: true
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/elig/allOrg:
    get:
      tags:
        - "Eligibility"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  # Home
  # /home:
  #   get:
  #     tags:
  #       - "Home"
  #     summary:
  #     description:
  #     operationId:
  #     consumes:
  #       - application/json
  #     produces:
  #       - application/json
  #     externalDocs:
  #     parameters:
  #     responses:
  #     deprecated:
  #     security:
  #     servers:
  #     requestBody:
  #     callbacks:

  # Inventory
  /v2/inv/myOrg:
    get:
      tags:
        - "Inventory"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:
    put:
      tags:
        - "Inventory"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              eligibility:
                type: integer
          required: true
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/inv/myOrgDispense:
    put:
      tags:
        - "Inventory"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/inv/allOrgs:
    get:
      tags:
        - "Inventory"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:


  # Provider
  /v2/org/myOrg:
    get:
      tags:
        - "Provider"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:
    put:
      tags:
        - "Provider"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              provider_name:
                type: string
              phone:
                type: string
              description:
                type: string
              hours:
                type: string
              days_of_operation:
                type: string
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/org/allSummary:
    get:
      tags:
        - "Provider"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/org/allFull:
    get:
      tags:
        - "Provider"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/org/addOne:
    post:
      tags:
        - "Provider"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              provider_name:
                type: string
              phone:
                type: string
              description:
                type: string
              hours:
                type: string
              days_of_operation:
                type: string
          required: true
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:



  # Referral
  /v2/refer/fromMyOrg:
    get:
      tags:
        - "Referral"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/refer/toMyOrg:
    get:
      tags:
        - "Referral"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks:

  /v2/refer/addOne:
    post:
      tags:
        - "Referral"
      summary:
      description:
      operationId:
      consumes:
        - application/json
      produces:
        - application/json
      externalDocs:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              referee_id:
                type: integer
              is_eligiable:
                type: boolean
              date_of_referal:
                type: integer
              referral_notes:
                type: string
              fulfillment_status:
                type: string
          required: true
      responses:
        200:
          description: Request Successful
        422:
          description: Invalid/Missing Parameters
      deprecated:
      security:
        - key
      servers:
      requestBody:
      callbacks: